apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-ha
  namespace: flask-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
