# Ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: foo.bar.com
      paths:
      - "/"
# Secret
db:
 rootpassword: passw

# Configmap
dbname: studentdb
host: db

# Deployment
replicaCount: 1
image:
  registry: ramirezy
  repository: flask-app
  version: "latest"
  name: mysql
  tag: "5.6"
  pullPolicy: IfNotPresent

# Service
service:
  type: "LoadBalancer"
  app: 5000
  port: 3306

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80


