# Ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: foo.bar.com
      paths:
      - "/"
# Secret
db:
  rootpassword: passw
  userpassword: secret12345
  username: usuariodb

# Configmap
dbname: studentdb
host: mysql

# Deployment
replicaCount: 1
image:
  app: "ramirezy/flask-app:latest"
  db: "mysql:5.6"
  pullPolicy: IfNotPresent

# Service
service:
  type: "LoadBalancer"
  app: 5000
  port: 3306

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80


