apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flaskapp.fullname" . }}-mysql-pv-claim
  namespace: {{ Release.Namespace }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
