apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flaskapp.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  rootpassword: {{ .Values.db.rootpassword | b64enc | quote }}

