apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flaskapp.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}  
    protocol: TCP
    targetPort: 5000
  selector:
    {{- include "flaskapp.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}

